language: generic
addons:
  homebrew:
    packages:
      - pyenv
matrix:
  include:
    - os: linux
      language: python
      python: "3.6"
    - os: linux
      language: python
      python: "3.7"
    - os: osx
      osx_image: xcode11
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.6"
    - os: osx
      osx_image: xcode11
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.7"

before_install:
  - .build/install_pyenv.sh

install:
  - pip install -U pip
  - pip install -U -r ci_requirements.txt

script:
  - TEST_PACKAGING=1 python -m coverage run --branch --source . -m unittest -v

after_success:
  - python -m coverage report --show-missing
  - codecov

notifications:
  email: false
